### ISSUE TITLE
Custom Animation

### ISSUE THREAD

**Issue by crixzgamez** [XxFri3ndlyxX/esx_lockpick#1]
Hi, currently using the blowtorch for the mechanic job and want the animation 
TaskPlayAnim(pid,"anim@amb@clubhouse@tutorial@bkr_tut_ig3@","machinic_loop_mechandplayer"
to function.
I am probably only missing a function for my script to work as I want it but im turning blind.
Do you have a quick fix for this?
obviously want the animation in a loop til the timer is out.

**Comment by XxFri3ndlyxX** [comment]
Check how I did in esx_illegal_drugs.

**Comment by XxFri3ndlyxX** [comment]
Next updated will have this implemented.

**Comment by XxFri3ndlyxX** [comment]
Animation added
