### ISSUE TITLE
Can still break in any car

### ISSUE THREAD

**Issue by TheRealDadbeard** [XxFri3ndlyxX/esx_lockpick#4]
Title. Everything starts and looks fine, can even buy the lockpick but it will still steal a car the old fashioned way

Edit: Name a dep is wrong in the __resource.lua. My folder is named mythic_progbar like in the github. Progressbar doesnt show up either.

Edit2: Yeah you have to change everything to progbar as nothing will show up then the script works fine, now looking into how to make it use the lockpick in the car and just smash the windows

**Comment by Demo4889** [comment]
@TheRealDadbeard 
The progress bars has to be downloaded from his link in the README.md file, otherwise the events are named mythic_progbar. Friendly has all theirs named as mythic_progressbar. You probably downloaded it directly from mythicrp where the events are named differently.
